### ISSUE TITLE
Mysterious oversized Greenovate logo

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#925] opened 2019-11-23 19:49 UTC
Greenovate logo on Guide to Climate Action is very large: https://content.boston.gov/take-action-climate-change

Testing on Google Chrome

Here's what test site looks like:
![Screen Shot 2019-11-23 at 2 46 06 PM](https://user-images.githubusercontent.com/28716225/69484361-4b0aa880-0e00-11ea-88ec-a936e060c047.png)

Here's what it looks like on Boston.gov:
![Screen Shot 2019-11-23 at 2 48 45 PM](https://user-images.githubusercontent.com/28716225/69484367-64abf000-0e00-11ea-8d3e-62cae466deb8.png)

**Comment by davidrkupton** [comment] 2019-11-23 23:44
is in fact a duplicate of #909

**Comment by davidrkupton** [comment] 2019-11-23 23:45
Hotifix will fix.

**Closed by davidrkupton** 2019-11-23 23:45 UTC
Labels: LAUNCH
