### ISSUE TITLE
Can't upload images to icon section of "features" taxonomy

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1142] opened 2019-12-26 14:23 UTC
The features taxonomy is located here: Structure > Taxonomy > Features

You can add "features" to our "place profile" content type to give a graphical display of the different options at the location. Currently, the icons are all broken on the site:
![image](https://user-images.githubusercontent.com/7929556/71479080-fe303e00-27c0-11ea-8497-74bf965c7dc9.png)

I went into each feature to upload a new version of the icon and noticed two errors. One, the icon upload wouldn't accept svg files. When I attempted to upload a png file, I get this error message:
![image](https://user-images.githubusercontent.com/7929556/71479168-4b141480-27c1-11ea-87b0-2439142ab15b.png)

I can't figure out a way to get the image to save.

**Comment by reillyzlab** [comment] 2019-12-26 21:23
Duplicate of #997 so closing

**Closed by reillyzlab** 2019-12-26 21:23 UTC
Labels: back end, bug, front end
