### ISSUE TITLE
Rename key menu items

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1095] opened 2019-12-16 15:38 UTC
This was one of General Assembly's recommendations. 

<img width="745" alt="Screen Shot 2019-12-16 at 10 37 44 AM" src="https://user-images.githubusercontent.com/57111927/70920184-231df780-1ff0-11ea-80ad-ac4ce47bcaf2.png">

**Comment by rachelsater** [comment] 2021-07-23 16:58
@duffy-james @Micah-Levine Do you feel we should make these changes? thanks

**Comment by duffy-james** [comment] 2021-08-31 17:09
@rachelsater the issue is, at this point, we've had our users working in Drupal with the current layout. This would have been great when we launched D8, but I'm not sure about the benefit at this point. Going to close this one out.

**Closed by duffy-james** 2021-08-31 17:09 UTC
Labels: enhancement, back end, Project - General Assembly UXDI
