### ISSUE TITLE
Icons overlapping text on mobile (Windows phone)

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#948] opened 2019-11-24 18:59 UTC
Testing using a Windows Nokia Lumia phone, icons are overlapping text on Boston.gov homepage
![Screen Shot 2019-11-24 at 1 59 01 PM](https://user-images.githubusercontent.com/28716225/69499667-8a99c900-0ec2-11ea-85d5-44a02d6e0cb9.png)

**Comment by subaha-cob** [comment] 2020-09-10 13:22
Fixed in a previous ticket.

**Comment by andrebtlima** [comment] 2020-09-11 18:33
@subaha-cob not sure this is fixed. It's definitely working for me on my iPhone, running Chrome, but when I switch to the Windows Nokia Lumia phone that @SarahFigalora used when she spotted the original issue, I'm still getting the same issue:

<img width="1429" alt="Screen Shot 2020-09-11 at 2 31 36 PM" src="https://user-images.githubusercontent.com/57111927/92960482-b8450400-f43b-11ea-8508-99ac5fd13075.png">

**Comment by subaha-cob** [comment] 2020-09-11 18:38
@andrebtlima. Okay, I will try and find a way to reproduce this bug. The Nokia Lumia simulator I have is not reproducing the bug. Moving back to in progress.

**Comment by subaha-cob** [comment] 2020-09-18 18:54
@andrebtlima I still cannot reproduce this. Can I get the specific Nokia Lumia Style? For example is it Nokia Lumia 920, 520, etc. Thanks!

**Comment by subaha-cob** [comment] 2020-09-23 18:28
@andrebtlima can you please do me a solid by writing down the steps you are using to reproduce this bug. Also include the browser you are using and the tool you are using to test. Thank you.

**Comment by subaha-cob** [comment] 2020-09-25 16:46
Test on: https://d8-uat.boston.gov/

**Closed** 2021-03-08 21:13 UTC
Labels: LAUNCH
