### ISSUE TITLE
Images styles missing/broken on media entity manager

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1017] opened 2019-11-29 20:46 UTC
Old title of ticket: "Full column wide (embedded)" option cutting off images in WYSIWYG

Looks like a height is being forced on the image:
![image](https://user-images.githubusercontent.com/7929556/69889510-455d0900-12bf-11ea-9044-8c1aaf12be27.png)

When I inspect the element, it looks like it's 423px for some reason:
![image](https://user-images.githubusercontent.com/7929556/69889523-5d348d00-12bf-11ea-8225-a810ab30344e.png)

**Comment by reillyzlab** [comment] 2019-12-09 18:24
Image styles are broken.

![Screen Shot 2019-12-09 at 1 23 40 PM](https://user-images.githubusercontent.com/20731897/70461694-47755380-1a87-11ea-9450-5597e1fb867c.png)

**Comment by andrebtlima** [comment] 2020-01-10 16:04
This ticket looks like a duplicate of #1162, which is in progress, so closing.

**Closed by andrebtlima** 2020-01-10 16:04 UTC
Labels: LAUNCH, REVIEWED, bug
