### ISSUE TITLE
SAML or some other SSO appears to be operating on boston.gov Drupal7 site. 

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#572] opened 2019-09-04 16:08 UTC
Need to verify if this need setup to replicate on D8.

**Comment by jimafisk** [comment] 2019-09-19 20:03
Our current D7 config.php looks very similar to https://www.chapterthree.com/blog/how-to-configure-simplesamlphp-for-drupal-8-on-acquia. We're trying to simplify this a bit on D8.

Currently we're getting "permission denied" for the `/simplesaml` path:

![simplesaml_symlink](https://user-images.githubusercontent.com/5913244/65276952-dd3bbb00-daf6-11e9-9290-5a04c946311a.png)

This is supposed to redirect to `/simplesaml/module.php/core/frontpage_welcome.php`, which we can still access directly.

**Comment by jimafisk** [comment] 2019-10-01 19:29
The "Permission denied" error was resolved by placing the `.htaccess` redirect conditions within `<IfModule mod_rewrite.c>`.

Resource for overriding settings and config in `settings.php`: https://www.valuebound.com/resources/blog/how-to-configure-single-sign-on-across-multiple-drupal-8-platforms-or-websites

These settings overrides do not appear in the UI (`/admin/config/people/simplesamlphp_auth`), which appears to be by design:
- https://drupal.stackexchange.com/questions/213897/configuration-override-not-work-from-settings-php
- https://www.drupal.org/project/drupal/issues/2408549

Resource for setting up memcached on acquia: https://github.com/acquia/memcache-settings

**Comment by reillyzlab** [comment] 2019-11-01 19:57
Tested on dev and staging and seems to be functionally working. I think ideally a user that goes to /user would be automatically redirected to sso log in rather than jumping to another page and then through to the sso page. We should discuss during weekly longer sync.

Need to also set up on production.

**Comment by jimafisk** [comment] 2019-11-01 20:22
Thanks for testing @reillyzlab!

The reason it doesn't go directly to sso at the moment is I'm trying to accommodate the same workflow as D7, which allows both SAML and Drupal logins:

<details>
<summary>SAML Login</summary>

![user](https://user-images.githubusercontent.com/5913244/68054033-c676af80-fcc3-11e9-8c5a-55b51173356b.png)

</details>
<details>
<summary>Drupal Login</summary>

![user_local](https://user-images.githubusercontent.com/5913244/68054029-c2e32880-fcc3-11e9-8d1b-d935fea03c9a.png)


</details>

**Comment by jimafisk** [comment] 2019-11-01 20:25
The same as ^ works on D8:

<details>
<summary>SAML Login</summary>

![saml](https://user-images.githubusercontent.com/5913244/68054166-1b1a2a80-fcc4-11e9-8d4b-041fca4ebc9a.png)

</details>
<details>
<summary>Drupal Login</summary>

![no_saml](https://user-images.githubusercontent.com/5913244/68054176-21100b80-fcc4-11e9-9965-5685de3159e6.png)

</details>

We just need to fix the way Drupal doesn't cache query params (like `?local`).

**Comment by reillyzlab** [comment] 2019-11-15 15:33
Issues logging into production on content. site

![Screen Shot 2019-11-15 at 10 31 17 AM](https://user-images.githubusercontent.com/20731897/68955006-1dd05180-0793-11ea-8cf6-6b95f796f6b2.png)

Plain text error:
No SAML response provided
You accessed the Assertion Consumer Service interface, but did not provide a SAML Authentication Response. Please note that this endpoint is not intended to be accessed directly.
If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:

e583f7a66dCopy to clipboard
Debug information
The debug information below may be of interest to the administrator / help desk:

SimpleSAML\Error\Error: ACSPARAMS
Backtrace:
2 modules/saml/www/sp/saml2-acs.php:22 (require)
1 lib/SimpleSAML/Module.php:236 (SimpleSAML\Module::process)
0 www/module.php:9 (N/A)
Caused by: Exception: Unable to find the current binding.
Backtrace:
3 vendor/simplesamlphp/saml2/src/SAML2/Binding.php:108 (SAML2\Binding::getCurrentBinding)
2 modules/saml/www/sp/saml2-acs.php:16 (require)
1 lib/SimpleSAML/Module.php:236 (SimpleSAML\Module::process)
0 www/module.php:9 (N/A)
Report errors
Optionally enter your email address, for the administrators to be able contact you for further questions about your issue:

E-mail address:  



Send error report

How to get help
This error probably is due to some unexpected behaviour or to misconfiguration of SimpleSAMLphp. Contact the administrator of this login service, and send them the error message above.

**Comment by reillyzlab** [comment] 2019-11-19 20:06
Not working. Loops back to log in screen when attempt to process credentials.

**Closed** 2019-11-24 20:26 UTC
Labels: launch-blocker
