### ISSUE TITLE
Summer in Boston Guide: Jamaica Plain Community Pool text format issues

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#486] opened 2019-08-05 20:55 UTC
Under 'Community Center Pools' Jamaica Plain BCYF Center text is formatted differently than the rest.

D7: https://www.boston.gov/summer-boston
![image](https://user-images.githubusercontent.com/42783424/62494492-a8231580-b7a1-11e9-95c6-22cff92e343b.png)

D8: http://bostond8dev.prod.acquia-sites.com/summer-boston
![image](https://user-images.githubusercontent.com/42783424/62494484-a6f1e880-b7a1-11e9-9991-c760b4f3825f.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment] 2019-08-07 14:07
Duplicate of #487.

**Closed by davidrkupton** 2019-08-07 14:07 UTC
Labels: duplicate, max-testing
