### ISSUE TITLE
Issue with masquerade feature functionality

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1056] opened 2019-12-09 16:58 UTC
Tested masquerade as mentioned in this pull request: https://github.com/CityOfBoston/boston.gov-d8/pull/1054

When Reilly is logged in using her Access Boston test credentials and tries to use masquerade, she gets taken to the following page:

![Screen Shot 2019-12-09 at 11 56 24 AM](https://user-images.githubusercontent.com/20731897/70456419-0f1c4800-1a7c-11ea-8e27-68093f0c70a4.png)

![Screen Shot 2019-12-09 at 11 57 05 AM](https://user-images.githubusercontent.com/20731897/70455941-2a3a8800-1a7b-11ea-9fee-10c3d9806615.png)

**Comment by rachelsater** [comment] 2021-08-20 19:34
Closing because we can't reproduce it. Can open new ticket if needed

**Closed by rachelsater** 2021-08-20 19:34 UTC
Labels: bug, back end
