### ISSUE TITLE
"Places" option in "list" component not working

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#649] opened 2019-09-20 16:41 UTC
When a user selects "places" in the list component, there aren't any options for the different places in the system:
![image](https://user-images.githubusercontent.com/7929556/65343637-72948900-dba3-11e9-924c-6d50efd5eaec.png)

Here's what it looks like in D7:
![image](https://user-images.githubusercontent.com/7929556/65343696-98219280-dba3-11e9-98f6-8bb5e965f737.png)

**Comment by reillyzlab** [comment] 2019-11-08 16:36
Verifying with @duffy-james whether this is a blocker or not.

**Comment by duffy-james** [comment] 2019-11-08 17:02
need to test again to confirm it's still an issue, but definitely a blocker.

**Comment by reillyzlab** [comment] 2019-11-08 17:13
This populates all 'place' pages on the site found found on D7 here: 

![Screen Shot 2019-11-08 at 12 12 40 PM](https://user-images.githubusercontent.com/20731897/68496784-194eea80-0221-11ea-8078-3561f02fee41.png) 

Currently, cannot populate without this functionality meaning handful of pages (linked from menu) would be missing.

**Comment by reillyzlab** [comment] 2021-04-08 15:38
Confirmed with James - closing

**Comment by reillyzlab** [comment] 2021-04-08 15:53
Details for later if needed:

Jim [Fiskl] / @davidrkupton used the "arguments" field to solve for this for the Drupal 7 to 8 migration

This 'solves' for the need, but isn't the most user friendly way to complete this. We could revisit if we wanted a better experience for content authors / editor. But, since these pages aren't updated that often this is not currently necessary/top priority. We can revisit later if need be/if this resurfaces.

![image](https://user-images.githubusercontent.com/20731897/114057840-ef0fbb00-9860-11eb-9a1f-8bc471fd0e8d.png)

Closing the ticket for now, but @davidrkupton feel free to add any other documentation that could be relevant if you see fit.




11:40
I have no idea what the number references
11:41

**Closed** 2021-04-08 15:53 UTC
Labels: back end
