### ISSUE TITLE
Current issues with "news" and "events" components

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#895] opened 2019-11-21 21:35 UTC
First, "related content" and the tagging process appears to be working.

We're still seeing styling issues with posts for "news" components:

![image](https://user-images.githubusercontent.com/7929556/69378345-33a2b280-0c7c-11ea-814d-f6ca737d1360.png)

The date is missing, and it doesn't have the indent that the other post has.

In the "featured item" field in the "events" component, it appears to only be surfacing "public notices" and not "events". I can't get any events to appear. Here is the field I'm referencing:

![image](https://user-images.githubusercontent.com/7929556/69378485-79f81180-0c7c-11ea-9f97-ef686495e42f.png)

**Comment by reillyzlab** [comment] 2019-11-22 16:03
Upcoming events aren't appearing on live dev site for anonymous users, but they are there for site admins.

Events are viewable to anonymous users, just not in the upcoming events component.

**Comment by jimafisk** [comment] 2019-11-22 17:40
Regarding the missing date, it looks like this is happening on new Post nodes when the `published_date` is not set. @davidrkupton is this supposed to be set programmatically?

<details>
<summary>Missing published date</summary>

![no_published_date](https://user-images.githubusercontent.com/5913244/69447578-cc8d0880-0d24-11ea-8278-325b2bb3e855.png)


</details>
<details>
<summary>Manually set published date</summary>

![set_published_date](https://user-images.githubusercontent.com/5913244/69447605-da428e00-0d24-11ea-80e0-8e17e0a10e0f.png)


</details>
<details>
<summary>The fixed display</summary>

![published_date_display](https://user-images.githubusercontent.com/5913244/69447651-ededf480-0d24-11ea-9c23-b640ba9073f1.png)


</details>

There are 3 viable options that come to mind:
1. Fix the logic that is supposed to set this automatically
2. Make this field required so we are forced to set it manually
3. Remove this field entirely and just use the default Drupal "authored date" that works automatically out of the box and appears to do the same thing

@duffy-james do you have a preference?

**Comment by duffy-james** [comment] 2019-11-22 18:00
@jimafisk I would prefer option 1. I know we've talked before about that being automatically updated when the state is changed from "draft" or "needs review" to published.

Option 3 sounds viable too, but I think we'd have to make sure there aren't any unintended consequences.

**Comment by jimafisk** [comment] 2019-11-22 18:04
Ok thanks!

@davidrkupton I think you worked on this logic originally, do you want to revisit that? It should automatically set the published date on Posts.

**Comment by jimafisk** [comment] 2019-11-22 18:18
Ok I figured out why only public notices were showing up, `field_featured_item` uses an entity reference view filter for the autocomplete functionality:

<details>
<summary>See field_featured_item settings</summary>

![entity_reference_view_filter](https://user-images.githubusercontent.com/5913244/69449959-0ad8f680-0d2a-11ea-89f5-e109930ea014.png)

</details>

That uses this View: https://boston.lndo.site/admin/structure/views/view/entity_reference_filters/edit/entity_reference_2

Since we updated the event dates to use date recur, it broke the filter on the view and so the or statement only returns results for public_notices. 

<details>
<summary>See broken handler in View</summary>

![broken_handler](https://user-images.githubusercontent.com/5913244/69450144-7cb14000-0d2a-11ea-99d3-00bd8e341467.png)

</details>

**Comment by duffy-james** [comment] 2019-11-22 18:21
one other thing, I noticed on the "post" content type, it's not displaying the "last updated" date. It's actually the published date:

![image](https://user-images.githubusercontent.com/7929556/69450383-05c87700-0d2b-11ea-8aa0-5ce133ec00ff.png)

https://d8-dev.boston.gov/news/test-post-0

**Comment by jimafisk** [comment] 2019-11-22 19:21
Ok I've fixed:
1. Make sure Events and Public Notices appear in the Featured Item autocomplete field for Events & Notices
2. Moved Updated Date above Published Date on the edit form for Posts
3. Displayed the Updated Date in the sidebar of a Post instead the Published Date

I think the only remaining work here is to make sure the Published Date gets set automatically when publishing a node. @davidrkupton I'll leave that to you since you originally worked on that and have a better idea how it's setup.

@duffy-james since for now you can manually set this date, is that something we can fix this next week after launch or is it a blocker? Thanks!

**Comment by reillyzlab** [comment] 2019-11-29 20:40
Duplicate of other issues so closing this one.

**Closed by reillyzlab** 2019-11-29 20:40 UTC
Labels: James, launch-blocker
