### ISSUE TITLE
Update: Adjust how to layout

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#320] opened 2019-04-08 16:45 UTC
Change layout to match what was proposed by General Assembly - progressive disclosure, excluding sidebar

Info here: https://drive.google.com/drive/u/0/folders/1_bojXdClHgiSD6R92mEqtE9sndXVUgdw

**Comment by reillyzlab** [comment] 2019-04-08 16:55
Dependent on this: https://github.com/CityOfBoston/creative-team-workflow/issues/1170

**Comment by jimafisk** [comment] 2019-05-07 16:49
Based on the annotated wireframe doc, it looks like the main change is removing the current horizontal tabs:

![horizontal_tabs](https://user-images.githubusercontent.com/5913244/57317506-4251bf80-70c6-11e9-943a-5ab0797d99f5.png)

and replacing with accordion-like vertical tabs:

![vertical_tabs](https://user-images.githubusercontent.com/5913244/57317515-45e54680-70c6-11e9-9e31-9705565f79c7.png)

**Comment by rachelsater** [comment] 2021-04-07 18:13
Closing this ticket because it's a duplicate of https://github.com/CityOfBoston/boston.gov-d8/issues/1808

**Closed by rachelsater** 2021-04-07 18:13 UTC
Labels: Project - Design improvements, enhancement
