### ISSUE TITLE
Mobile: date formatting is off on Boston.gov homepage

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#732] opened 2019-10-02 20:39 UTC
Found on Safari, iPhone 6s

Date breaks onto two lines, but should remain on one line.

![IMG-5797](https://user-images.githubusercontent.com/28716225/66079929-14688e00-e533-11e9-8af6-6e55501df226.PNG)

**Comment by reillyzlab** [comment] 2021-04-05 21:00
There is a duplicate of this so closing this one.

**Closed by reillyzlab** 2021-04-05 21:00 UTC
Labels: mobile
