### ISSUE TITLE
Logo issue on 'program/initiative profile' type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#986] opened 2019-11-25 19:28 UTC
The logo is displaying extra meta tag information on the live site:
![image](https://user-images.githubusercontent.com/7929556/69571282-bb93ff80-0f8f-11ea-9c2c-58fe3f85aee9.png)

The logo section is located here in the backend:
![image](https://user-images.githubusercontent.com/7929556/69571327-d9f9fb00-0f8f-11ea-9a94-2be0fa5c6cf5.png)

Example page:
https://www.boston.gov/housing/boston-home-center

**Comment by reillyzlab** [comment] 2019-11-25 21:57
Duplicate of #946 so closing this but will link to it in 946.

**Closed** 2019-11-25 21:58 UTC
Labels: LAUNCH
